version: '3.9'
services:
  nr-controller:   
    public: true
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID="NR-Controller"
        - NR_DB_USER=${NR_DB_USER}
        - NR_DB_PASS=${NR_DB_PASS}
        - NR_DB_HOST=${NR_DB_HOST}
        - NR_NAMESPACE=${NR_NAMESPACE}
    ports:
      - 1880
      
  nr-worker1:   
    public: true
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID="NR-Worcker_ns1"
        - NR_DB_USER=${NR_DB_USER}
        - NR_DB_PASS=${NR_DB_PASS}
        - NR_DB_HOST=${NR_DB_HOST}
        - NR_NAMESPACE=${NR_NAMESPACE}
    ports:
      - 1880
      
  nr-worker1:   
    public: true
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID="NR-Worcker_ns2"
        - NR_DB_USER=${NR_DB_USER}
        - NR_DB_PASS=${NR_DB_PASS}
        - NR_DB_HOST=${NR_DB_HOST}
        - NR_NAMESPACE=${NR_NAMESPACE}
    ports:
      - 1880

  nr-worker3:   
    public: true
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID="NR-Worcker_ns3"
        - NR_DB_USER=${NR_DB_USER}
        - NR_DB_PASS=${NR_DB_PASS}
        - NR_DB_HOST=${NR_DB_HOST}
        - NR_NAMESPACE=${NR_NAMESPACE}
    ports:
      - 1880
