version: '3.9'
services:
  nr-controller:   
    public: true
    hostname: nr-controller
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID=NR-Controller-ns0
        - NR_DB_USER=${USER}
        - NR_DB_PASS=${PASS}
        - NR_DB_HOST=${HOST}
        - NR_NAMESPACE=${OKTETO_NAMESPACE}
        - NR_IP=${BUILDKIT_HOST}
        - NR_TYPE=ControllerPackage.json 
    ports:
      - 1880
      
  nr-worker1:   
    public: true
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID=NR-Worker-ns1
        - NR_DB_USER=${USER}
        - NR_DB_PASS=${PASS}
        - NR_DB_HOST=${HOST}
        - NR_NAMESPACE=${OKTETO_NAMESPACE}
        - NR_TYPE=WorkerPackage.json
    ports:
      - 1880
      
  nr-worker2:   
    public: true
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID=NR-Wocker-ns2
        - NR_DB_USER=${USER}
        - NR_DB_PASS=${PASS}
        - NR_DB_HOST=${HOST}
        - NR_NAMESPACE=${OKTETO_NAMESPACE}
        - NR_TYPE=WorkerPackage.json
    ports:
      - 1880

  nr-worker3:   
    public: true
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID=NR-Worker-ns3
        - NR_DB_USER=${USER}
        - NR_DB_PASS=${PASS}
        - NR_DB_HOST=${HOST}
        - NR_NAMESPACE=${OKTETO_NAMESPACE}
        - NR_TYPE=WorkerPackage.json
    ports:
      - 1880
